org.gradle.jvmargs=-Xmx2048M

minecraft_version = 1.20.1
minecraft_min_version = 1.20
minecraft_max_version = 1.20.2
enabled_platforms = fabric,forge

mod_id = differentdoors
mod_name = Different Doors
mod_version = 1.0.0
mod_license = MIT
mod_authors = ChefMooon
mod_description = Basic doors
mod_homepage = https://github.com/ChefMooon/different-doors
mod_issues = https://github.com/ChefMooon/different-doors/issues
mod_github = https://github.com/ChefMooon/different-doors
mod_discord = https://discord.gg/mbuDBHHUws
mod_credits = ChefMooon

minecraft_supported_versions = 1.20.1
# STABLE, BETA, ALPHA
mod_version_type = STABLE
mod_build_number = 0
modrinth_project_id = qKALU9V7
curseforge_project_id = 1347779

archives_base_name = differentdoors
maven_group = com.differentdoors

fabric_loader_version = 0.16.10
fabric_api_version = 0.92.6+1.20.1

parchment_version = 1.20.1:2023.09.03

neoforge_version = 21.1.79
forge_version = 47.4.10
